name: InDeciple
version: 1.0.0
author: Zecterma
depend: [Vault]
main: me.Zecterma.InDeciple.InDeciple

commands:
  indeciple:
    description: InDeciple Main command.
    
  indeciplereload:
    description: InDeciple config reload.
    
  indeciplelist:
    description: InDeciple Commands List
    
  g:
    description: Change gamemode.
    
  freeze:
    description: Freeze yourself or other players
    
  set:
    description: Gives you the item set you want.

    
permissions:
  indeciple.*:
    default: op
    description: Access to all InDeciple commands
    children:
      indeciple.indeciple: true
      indeciple.g: true
      indeciple.reload: true
      indeciple.list: true
      indeciple.freeze: true
      indeciple.freeze.others: true
      indeciple.set: true
  indeciple.indeciple:
    default: op
    description: Permission to /indeciple
  indeciple.g:
    default: op
    description: Permission to /g
  indeciple.list:
    default: op
    description: Permission to /indeciplelist
  indeciple.reload:
    default: op
    description: Permission to /indeciplereload
  indeciple.freeze:
    default: op
    description: Permissions to /freeze
  indeciple.freeze.others:
    default: op
    description: Permissions to /freeze <name>
  indeciple.set:
    default: op
    description: Permission to /set <itemset>