name: InDeciple
version: 1.0.0
author: Zecterma
depend: [Vault]
main: me.Zecterma.InDeciple.InDeciple

commands:
  indeciple:
    description: InDeciple Main command.
    
  indeciplereload:
    description: InDeciple config reload.
    
  indeciplelist:
    description: InDeciple Commands List
    
  g:
    description: Change gamemode.

    
permissions:
  indeciple.indeciple:
    default: op
    description: Permission to /indeciple
  indeciple.g:
    default: op
    description: Permission to /g
  indeciple.list:
    default: op
    description: Permission to /indeciplelist
  indeciple.reload:
    default: op
    description: Permission to /indeciplereload