name: InDeciple
version: 1.0.0
author: Zecterma
depend: [Vault]
main: me.Zecterma.InDeciple.InDeciple

commands:
  indeciple:
    description: InDeciple Main command.
    usage: /InDeciple
    aliases: [indeciple]
  indeciple list:
    description: InDeciple Commands List
    usage: /InDeciple list
    aliases: [indeciple list]
    
permissions:
  indeciple.indeciple:
    default: op
    description: This permission allowes you to use /InDeciple